/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/carta` | `/carta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/carta` | `/carta`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/mesas` | `/mesas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/carta${`?${string}` | `#${string}` | ''}` | `/carta${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/mesas${`?${string}` | `#${string}` | ''}` | `/mesas${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/carta` | `/carta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
